global using KeyDb.Shared.Helpers;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using KeyDb;
global using Microsoft.Extensions.DependencyInjection;
global using KeyDb.Shared;
global using Microsoft.EntityFrameworkCore;
global using Serilog;
global using KeyDb.Shared.Models;
